# Generated by Django 3.2.9 on 2021-11-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0002_reservation_flight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='flight',
            new_name='flight_name',
        ),
    ]
