# Generated by Django 3.2.9 on 2021-11-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0003_rename_flight_reservation_flight_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='flightNumber',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
